import type { ProviderView } from "./types";

/** Mirrors openhanako desktop/src/react/utils/provider-presets.ts (+ vision-capable extras). */
export interface VisionProviderTemplate {
  id: string;
  label: string;
  labelZh: string;
  hint: string;
  hintZh: string;
  provider: Omit<ProviderView, "keySet">;
  visionModel: string;
}

function tpl(
  id: string,
  label: string,
  labelZh: string,
  hint: string,
  hintZh: string,
  name: string,
  kind: string,
  baseUrl: string,
  apiKeyEnv: string,
  models: string[],
  visionModel: string,
  contextWindow = 128_000,
): VisionProviderTemplate {
  return {
    id,
    label,
    labelZh,
    hint,
    hintZh,
    visionModel,
    provider: {
      name,
      kind,
      baseUrl,
      models,
      default: visionModel,
      apiKeyEnv,
      balanceUrl: "",
      contextWindow,
    },
  };
}

export const VISION_PROVIDER_TEMPLATES: VisionProviderTemplate[] = [
  tpl(
    "dashscope",
    "Alibaba DashScope (Qwen VL)",
    "阿里 DashScope（通义千问 VL）",
    "Compatible API at dashscope.aliyuncs.com — key from dashscope.aliyun.com",
    "DashScope 兼容接口 — 在 dashscope.aliyun.com 获取 API Key",
    "dashscope-vision",
    "openai",
    "https://dashscope.aliyuncs.com/compatible-mode/v1",
    "DASHSCOPE_API_KEY",
    ["qwen-vl-max", "qwen-vl-plus", "qwen3-vl-plus", "qwen3-vl-flash-2026-01-22"],
    "qwen-vl-max",
  ),
  tpl(
    "openai",
    "OpenAI (GPT-4o)",
    "OpenAI（GPT-4o）",
    "Official OpenAI API — key from platform.openai.com",
    "OpenAI 官方接口 — 在 platform.openai.com 获取 API Key",
    "openai-vision",
    "openai",
    "https://api.openai.com/v1",
    "OPENAI_API_KEY",
    ["gpt-4o", "gpt-4o-mini", "gpt-4.1", "gpt-4.1-mini"],
    "gpt-4o",
  ),
  tpl(
    "anthropic",
    "Anthropic (Claude)",
    "Anthropic（Claude）",
    "Claude Messages API — key from console.anthropic.com",
    "Claude 接口 — 在 console.anthropic.com 获取 API Key",
    "anthropic-vision",
    "anthropic",
    "https://api.anthropic.com",
    "ANTHROPIC_API_KEY",
    ["claude-sonnet-4-5", "claude-opus-4-6", "claude-sonnet-4-6"],
    "claude-sonnet-4-5",
  ),
  tpl(
    "moonshot",
    "Moonshot (Kimi K2.5)",
    "Moonshot（Kimi K2.5）",
    "OpenAI-compatible API — base_url https://api.moonshot.cn/v1, key from platform.kimi.com/console/api-keys",
    "Kimi 开放平台兼容接口 — base_url 为 https://api.moonshot.cn/v1，在 platform.kimi.com 控制台创建 API Key",
    "moonshot-vision",
    "openai",
    "https://api.moonshot.cn/v1",
    "MOONSHOT_API_KEY",
    ["kimi-k2.6", "kimi-k2.5", "kimi-latest", "moonshot-v1-8k-vision-preview"],
    "kimi-k2.5",
  ),
  tpl(
    "zhipu",
    "Zhipu (GLM-V)",
    "智谱（GLM 视觉）",
    "GLM OpenAI-compatible API — key from open.bigmodel.cn",
    "智谱开放平台 — 在 open.bigmodel.cn 获取 API Key",
    "zhipu-vision",
    "openai",
    "https://open.bigmodel.cn/api/paas/v4",
    "ZHIPU_API_KEY",
    ["glm-4v-flash", "glm-4-plus", "glm-5v-turbo"],
    "glm-4v-flash",
  ),
  tpl(
    "siliconflow",
    "SiliconFlow",
    "SiliconFlow（硅基流动）",
    "OpenAI-compatible aggregator — key from cloud.siliconflow.cn",
    "硅基流动聚合接口 — 在 cloud.siliconflow.cn 获取 API Key",
    "siliconflow-vision",
    "openai",
    "https://api.siliconflow.cn/v1",
    "SILICONFLOW_API_KEY",
    ["Qwen/Qwen2-VL-72B-Instruct", "OpenGVLab/InternVL2-8B", "qwen3-vl-plus"],
    "Qwen/Qwen2-VL-72B-Instruct",
  ),
  tpl(
    "volcengine",
    "Volcengine (Doubao Vision)",
    "火山引擎（豆包视觉）",
    "ByteDance Ark API — key from volcengine console",
    "火山方舟接口 — 在火山引擎控制台获取 API Key",
    "volcengine-vision",
    "openai",
    "https://ark.cn-beijing.volces.com/api/v3",
    "VOLCENGINE_API_KEY",
    ["doubao-vision-pro-32k", "doubao-vision-lite-32k", "doubao-seed-1-6-flash-250828"],
    "doubao-vision-pro-32k",
  ),
  tpl(
    "openrouter",
    "OpenRouter",
    "OpenRouter",
    "Multi-provider gateway — key from openrouter.ai",
    "多模型聚合网关 — 在 openrouter.ai 获取 API Key",
    "openrouter-vision",
    "openai",
    "https://openrouter.ai/api/v1",
    "OPENROUTER_API_KEY",
    ["openai/gpt-4o", "anthropic/claude-3.5-sonnet", "google/gemini-2.5-flash"],
    "openai/gpt-4o",
  ),
  tpl(
    "groq",
    "Groq",
    "Groq",
    "Fast inference API — key from console.groq.com",
    "Groq 推理接口 — 在 console.groq.com 获取 API Key",
    "groq-vision",
    "openai",
    "https://api.groq.com/openai/v1",
    "GROQ_API_KEY",
    ["meta-llama/llama-4-maverick-17b-128e-instruct", "meta-llama/llama-4-scout-17b-16e-instruct"],
    "meta-llama/llama-4-maverick-17b-128e-instruct",
  ),
  tpl(
    "mistral",
    "Mistral (Pixtral)",
    "Mistral（Pixtral）",
    "Mistral API — key from console.mistral.ai",
    "Mistral 接口 — 在 console.mistral.ai 获取 API Key",
    "mistral-vision",
    "openai",
    "https://api.mistral.ai/v1",
    "MISTRAL_API_KEY",
    ["pixtral-large-latest", "mistral-large-latest", "mistral-medium-latest"],
    "pixtral-large-latest",
  ),
  tpl(
    "xai",
    "xAI (Grok Vision)",
    "xAI（Grok 视觉）",
    "Grok API — key from x.ai/api",
    "Grok 接口 — 在 x.ai/api 获取 API Key",
    "xai-vision",
    "openai",
    "https://api.x.ai/v1",
    "XAI_API_KEY",
    ["grok-2-vision", "grok-2-vision-latest", "grok-4"],
    "grok-2-vision",
  ),
  tpl(
    "together",
    "Together AI",
    "Together AI",
    "Together inference API — key from together.ai",
    "Together 推理接口 — 在 together.ai 获取 API Key",
    "together-vision",
    "openai",
    "https://api.together.xyz/v1",
    "TOGETHER_API_KEY",
    ["Qwen/Qwen2-VL-72B-Instruct", "meta-llama/Llama-4-Scout-17B-16E-Instruct"],
    "Qwen/Qwen2-VL-72B-Instruct",
  ),
  tpl(
    "stepfun",
    "StepFun",
    "阶跃星辰（StepFun）",
    "StepFun API — key from platform.stepfun.com",
    "阶跃星辰接口 — 在 platform.stepfun.com 获取 API Key",
    "stepfun-vision",
    "openai",
    "https://api.stepfun.com/v1",
    "STEPFUN_API_KEY",
    ["step-1v-8k", "step-1v-32k", "step-3.5-flash"],
    "step-1v-8k",
  ),
  tpl(
    "hunyuan",
    "Tencent Hunyuan",
    "腾讯混元",
    "Hunyuan API — key from cloud.tencent.com",
    "腾讯混元接口 — 在腾讯云控制台获取 API Key",
    "hunyuan-vision",
    "openai",
    "https://api.hunyuan.cloud.tencent.com/v1",
    "HUNYUAN_API_KEY",
    ["hunyuan-vision-latest", "hunyuan-turbos-latest"],
    "hunyuan-vision-latest",
  ),
  tpl(
    "modelscope",
    "ModelScope",
    "魔搭 ModelScope",
    "ModelScope inference API — key from modelscope.cn",
    "魔搭推理接口 — 在 modelscope.cn 获取 API Key",
    "modelscope-vision",
    "openai",
    "https://api-inference.modelscope.cn/v1",
    "MODELSCOPE_API_KEY",
    ["qwen-vl-max", "qwen-vl-plus", "qwen3-vl-plus"],
    "qwen-vl-max",
  ),
  tpl(
    "kimi-coding",
    "Kimi Coding Plan",
    "Kimi Coding 套餐",
    "Requires Kimi Coding subscription key — https://api.kimi.com/coding/v1 (different from platform.kimi.com pay-as-you-go MOONSHOT_API_KEY)",
    "Kimi Coding 套餐专用 Key — 接口 https://api.kimi.com/coding/v1（与 platform.kimi.com 按量付费的 MOONSHOT_API_KEY 不是同一套）",
    "kimi-coding-vision",
    "openai",
    "https://api.kimi.com/coding/v1",
    "KIMI_API_KEY",
    ["kimi-k2.6", "kimi-for-coding", "kimi-k2.5", "kimi-k2"],
    "kimi-k2.6",
  ),
  tpl(
    "minimax",
    "MiniMax",
    "MiniMax",
    "MiniMax Anthropic-compatible API — key from minimaxi.com",
    "MiniMax 接口 — 在 minimaxi.com 获取 API Key",
    "minimax-vision",
    "anthropic",
    "https://api.minimaxi.com/anthropic",
    "MINIMAX_API_KEY",
    ["MiniMax-M3"],
    "MiniMax-M3",
  ),
  tpl(
    "mimo",
    "Xiaomi MiMo",
    "小米 MiMo",
    "MiMo OpenAI-compatible API — key from xiaomimimo.com",
    "小米 MiMo 接口 — 在 xiaomimimo.com 获取 API Key",
    "mimo-vision",
    "openai",
    "https://api.xiaomimimo.com/v1",
    "MIMO_API_KEY",
    ["mimo-v2-omni", "mimo-v2.5"],
    "mimo-v2-omni",
  ),
  tpl(
    "ollama",
    "Ollama (Local)",
    "Ollama（本地）",
    "Local Ollama server — run `ollama pull llava` first; API key can be any placeholder",
    "本地 Ollama — 先运行 `ollama pull llava`；API Key 可填任意占位符",
    "ollama-vision",
    "openai",
    "http://localhost:11434/v1",
    "OLLAMA_API_KEY",
    ["llava", "llava:13b", "gemma3"],
    "llava",
    32_000,
  ),
];

export function visionTemplateLabel(t: VisionProviderTemplate, locale: string): string {
  return locale.startsWith("zh") ? t.labelZh : t.label;
}

export function visionTemplateHint(t: VisionProviderTemplate, locale: string): string {
  return locale.startsWith("zh") ? t.hintZh : t.hint;
}
